name: semainetsaison
description: Apprends les jours de la semaine,les mois et les saisons.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  event_bus: ^1.1.1
  get: ^2.10.1
  provider: ^4.0.2
  path_provider: ^1.6.10
  http: ^0.12.0+4
  after_layout: ^1.0.7+2
  confetti: ^0.4.0
  video_player: ^0.10.8+1
  assets_audio_player: ^1.3.7+1
  flutter_tts: ^0.9.1
  avatar_glow: ^1.1.0
  auto_animated: ^2.0.2
  simple_animations: ^1.3.6
  giffy_dialog: ^1.7.0
  dotted_border: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  build_runner: ^1.8.1

flutter_icons:
  android: "ic_launcher"
  image_path_android: "icons/icon-android.png"
  ios: true
  image_path_ios: "icons/icon-ios.png"

flutter_native_splash:
  image: "icons/splash.png"
  color: "264467"
  android_disable_fullscreen: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/thumbs/
    - assets/sounds/
    - assets/data/

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/Montserrat-Alternates/MontserratAlternates-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Alternates/MontserratAlternates-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Alternates/MontserratAlternates-Light.ttf
          weight: 300          
        - asset: assets/fonts/Montserrat-Alternates/MontserratAlternates-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Alternates/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Alternates/MontserratAlternates-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Alternates/MontserratAlternates-Bold.ttf
          weight: 700        